
- name: Deploy app
  hosts: app
  become: true

  tasks:
    - name: Fetch the latest version of application code
      git:
        repo: 'https://github.com/express42/reddit.git'
        dest: /home/ubuntu/reddit
        version: monolith # <-- Указываем нужную ветку

    - name: Bundle install
      bundler:
        state: present
        chdir: /home/ubuntu/reddit
      notify: restart puma

  handlers:
    - name: restart puma
      systemd: name=puma state=restarted
