
- name: Configure hosts & deploy application
  hosts: all
  vars:
    mongo_bind_ip: 0.0.0.0
    db_host: "{{ hostvars['dbserver']['ansible_all_ipv4_addresses'][0] }}"

  tasks:
    - name: Fetch the latest version of application code
      git:
        repo: 'https://github.com/express42/reddit.git'
        dest: /home/ubuntu/reddit
        version: monolith # <-- Указываем нужную ветку
      tags: deploy-tag
      # notify: reload puma

    - name: Bundle install
      bundler:
        state: present
        chdir: /home/ubuntu/reddit
      tags: deploy-tag

    - name: Change mongo config file
      become: true
      template:
        src: templates/mongodb.conf.j2
        dest: /etc/mongodb.conf
        mode: 0644
      tags: db-tag
      notify: restart mongodb

    - name: Add to config for DB connect
      template:
        src: templates/db_config.j2
        dest: /home/ubuntu/db_config
      tags: app-tag

    - name: Add unit file for Puma
      become: true
      copy:
        src: files/puma.service
        dest: /etc/systemd/system/puma.service
      tags: app-tag

    - name: enable puma
      become: true
      systemd: name=puma enabled=yes
      tags: app-tag
      notify: reload puma



  handlers:
    - name: restart mongodb
      become: true
      service: name=mongodb state=restarted

    - name: reload puma
      become: true
      systemd: name=puma state=restarted
